-- 코드를 입력하세요
SELECT PRODUCT_CODE,
(
SELECT SUM(SALES_AMOUNT)
FROM OFFLINE_SALE
WHERE PRODUCT_ID=P.PRODUCT_ID
GROUP BY PRODUCT_ID
) * PRICE AS SALES 

FROM PRODUCT AS P #JOIN OFFLINE_SALE USING (PRODUCDT_ID)
ORDER BY SALES DESC, PRODUCT_CODE ASC