SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM FISH_INFO AS I JOIN FISH_NAME_INFO AS N USING (FISH_TYPE)
WHERE I.LENGTH= # 같은 FISH_TYPE을 가지면서 LENGTH가 최대인 애의 값과 같아야 함
(
SELECT MAX(LENGTH)
FROM FISH_INFO
WHERE I.FISH_TYPE=FISH_TYPE
GROUP BY FISH_TYPE
)
ORDER BY I.ID ASC