SELECT I.ID,N.FISH_NAME,I.LENGTH
FROM FISH_INFO AS I JOIN FISH_NAME_INFO AS N USING (FISH_TYPE)
WHERE I.LENGTH=(
SELECT MAX(LENGTH) FROM FISH_INFO 
WHERE I.FISH_TYPE=FISH_TYPE GROUP BY FISH_TYPE
)
ORDER BY I.ID