
SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO AS I JOIN FISH_NAME_INFO AS N USING (FISH_TYPE)
WHERE I.LENGTH =(
SELECT MAX(LENGTH)
FROM FISH_INFO
WHERE I.FISH_TYPE=FISH_TYPE
GROUP BY FISH_TYPE
)
ORDER BY ID ASC
# I의 LENGTH가 해당 FIHS_TYPE의 MAX(LENGTH) 와 일치해야 함